# Generated by Django 3.1.5 on 2021-01-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210131_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_uipdated',
            new_name='date_updated',
        ),
    ]
