# Generated by Django 3.1.5 on 2021-10-07 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210202_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='notes.note')),
                ('easiness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('interval', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('due_date', models.DateField()),
                ('last_reviewed', models.DateField(auto_now=True)),
            ],
        ),
    ]
